language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/php-coveralls -v

matrix:
  allow_failures:
  - php: nightly
